title: Healthcare x AI
author: dcstang
email: N/A
description: Medicine, Mind & Machine.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: David Tang
  tagline: Machine, Mind & Medicine.
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  dcstang
    linkedIn: david-tang-mrcp
    kaggle: dcstang


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - home.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

#making default frontmatter
#defaults:
#  -
#    scope:
#      path:
#      type:
#    values:
#      #values here
#      layout:
